name: Release Notes

on:
  push:
    branches:
      - main

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate release notes
      uses: release-drafter/release-drafter@v5.23.0
      id: drafter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sort-by: semver
        template: |
          ## Changes
          $CHANGES

          ## Commits
          $COMMITS
          $VERSIONS

    - name: Create release
      uses: actions/create-release@v1.1.4
      with:
        tag_name: ${{ steps.drafter.outputs.tag_name }}
        release_name: ${{ steps.drafter.outputs.release_name }}
        body: ${{ steps.drafter.outputs.body }}
